version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    network_mode: bridge
    depends_on:
      - nodejs
    links:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    volumes:
      - .:/usr/src/service/
    network_mode: bridge
