version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    network_mode: bridge
    ports:
      - "8000:80"
    depends_on:
      - flask
    links:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask:0.1
    container_name: flask-app
    network_mode: bridge
    command: flask run --host=0.0.0.0
    volumes:
      - ./python/:/code/
    environment:
      - FLASK_APP=/code/main.py
